version: "2"

services:
  redis:
    image: registry.fedoraproject.org/f31/redis
    container_name: redis
    ports:
      - 6379:6379
    user: "123123"

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      REDIS_HOST: redis
      REDIS_PORT: "6379"
    ports:
      - 8081:8081
    depends_on:
      - redis
    user: "123123"

  flower:
    image: mher/flower
    container_name: flower
    ports:
      - 5555:5555
    depends_on:
      - redis
    environment:
      FLOWER_DEBUG: "True"
      CELERY_BROKER_URL: redis://redis:6379/0
    user: "123123"

  postgres:
    container_name: postgres
    image: registry.access.redhat.com/rhscl/postgresql-10-rhel7
    environment:
      POSTGRESQL_USER: packit
      POSTGRESQL_PASSWORD: secret-password
      POSTGRESQL_DATABASE: packit
    ports:
      - 5432:5432

  worker:
    container_name: worker
    build:
      context: .
      dockerfile: files/docker/Dockerfile.worker
      args:
        SOURCE_BRANCH: master
    image: docker.io/usercont/packit-service-worker:dev
    command: /usr/bin/run_worker.sh
    tty: true
    depends_on:
      - redis
      - postgres
    environment:
      DEPLOYMENT: dev
      REDIS_SERVICE_HOST: redis
      APP: packit_service.worker.tasks
      KRB5CCNAME: FILE:/tmp/krb5cc_packit
      POSTGRESQL_USER: packit
      POSTGRESQL_PASSWORD: secret-password
      POSTGRESQL_DATABASE: packit
    volumes:
      - ./packit_service:/src/packit_service:ro,z
      # worker should not require packit-service.yaml
      - ./secrets/dev/packit-service.yaml:/home/packit/.config/packit-service.yaml:ro,z
      - ./secrets/dev/copr:/home/packit/.config/copr:ro,z
      - ./secrets/dev/ssh_config:/packit-ssh/config:ro,z
      - ./secrets/dev/id_rsa.pub:/packit-ssh/id_rsa.pub:ro,z
      - ./secrets/dev/id_rsa:/packit-ssh/id_rsa:ro,z
      - ./secrets/dev/fedora.keytab:/secrets/fedora.keytab:ro,z
      - ./secrets/dev/private-key.pem:/secrets/private-key.pem:ro,z
      #- .:/src:ro,z
    user: "123123"

  service:
    container_name: service
    build:
      context: .
      dockerfile: files/docker/Dockerfile
      args:
        SOURCE_BRANCH: master
    image: docker.io/usercont/packit-service:dev
    command: /usr/bin/run_httpd.sh
    depends_on:
      - redis
      - postgres
    ports:
      - 8443:8443
    environment:
      DEPLOYMENT: dev
      REDIS_SERVICE_HOST: redis
      POSTGRESQL_USER: packit
      POSTGRESQL_PASSWORD: secret-password
      POSTGRESQL_DATABASE: packit
    volumes:
      - ./packit_service:/usr/local/lib/python3.7/site-packages/packit_service:ro,z
      - ./files/packit-httpd.conf:/etc/httpd/conf.d/packit-httpd.conf:ro,z
      # There's no secrets/ by default. You have to create (or symlink to other dir) it yourself.
      # Make sure to set `command_handler: local` since there is no kube in d-c
      - ./secrets/dev/packit-service.yaml:/home/packit/.config/packit-service.yaml:ro,z
      - ./secrets/dev/fedora.keytab:/secrets/fedora.keytab:ro,z
      - ./secrets/dev/private-key.pem:/secrets/private-key.pem:ro,z
      - ./secrets/dev/fullchain.pem:/secrets/fullchain.pem:ro,z
      - ./secrets/dev/privkey.pem:/secrets/privkey.pem:ro,z
    user: "123123"

  fedora-messaging:
    container_name: fedora-messaging
    image: docker.io/usercont/packit-service-fedmsg:dev
    depends_on:
      - redis
    environment:
      DEPLOYMENT: dev
      FEDORA_MESSAGING_CONF: /home/packit/.config/fedora.toml
      REDIS_SERVICE_HOST: redis
    volumes:
      # get it from secrets
      - ./secrets/dev/fedora.toml:/home/packit/.config/fedora.toml:ro,Z
    user: "123123"

  centosmsg:
    container_name: centosmsg
    image: docker.io/usercont/packit-service-centosmsg:dev
    depends_on:
      - redis
    environment:
      DEPLOYMENT: dev
      LOG_LEVEL: DEBUG
      REDIS_SERVICE_HOST: redis
    volumes:
      - ./secrets/dev/centos-server-ca.cert:/secrets/centos-server-ca.cert:ro,Z
      - ./secrets/dev/centos.cert:/secrets/centos.cert:ro,Z
    user: "123123"

  adminer:
    image: adminer
    container_name: adminer
    depends_on:
      - postgres
    ports:
      - 8082:8080
    user: "123123"
