version: "2"

services:
  redis:
    image: quay.io/centos7/redis-5-centos7
    container_name: redis
    ports:
      - 6379:6379
    user: "1024"

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: docker.io/rediscommander/redis-commander
    environment:
      REDIS_HOST: redis
      REDIS_PORT: "6379"
    ports:
      - 8081:8081
    depends_on:
      - redis
    user: "1024"

  flower:
    image: docker.io/mher/flower
    container_name: flower
    ports:
      - 5555:5555
    depends_on:
      - redis
    environment:
      FLOWER_DEBUG: "True"
      CELERY_BROKER_URL: redis://redis:6379/0
    user: "1024"

  postgres:
    container_name: postgres
    image: quay.io/centos7/postgresql-13-centos7
    environment:
      POSTGRESQL_USER: packit
      POSTGRESQL_PASSWORD: secret-password
      POSTGRESQL_DATABASE: packit
    ports:
      - 5432:5432

  worker:
    container_name: worker
    build:
      context: .
      dockerfile: files/docker/Dockerfile.worker
      args:
        SOURCE_BRANCH: main
    image: quay.io/packit/packit-worker:dev
    command: /usr/bin/run_worker.sh
    #tty: true
    depends_on:
      - redis
      - postgres
    environment:
      DEPLOYMENT: dev
      REDIS_SERVICE_HOST: redis
      APP: packit_service.worker.tasks
      KRB5CCNAME: FILE:/tmp/krb5cc_packit
      POSTGRESQL_USER: packit
      POSTGRESQL_PASSWORD: secret-password
      POSTGRESQL_HOST: postgres
      POSTGRESQL_DATABASE: packit
      CELERY_RETRY_LIMIT: 0
      PUSHGATEWAY_ADDRESS: ""
      AWS_ACCESS_KEY_ID: ""
      AWS_SECRET_ACCESS_KEY: ""
    volumes:
      - ./packit_service:/usr/local/lib/python3.9/site-packages/packit_service:ro,z
      # worker should not require packit-service.yaml
      - ./secrets/packit/dev/packit-service.yaml:/home/packit/.config/packit-service.yaml:ro,z
      - ./secrets/packit/dev/copr:/home/packit/.config/copr:ro,z
      - ./secrets/packit/dev/ssh_config:/packit-ssh/config:ro,z
      - ./secrets/packit/dev/id_rsa.pub:/packit-ssh/id_rsa.pub:ro,z
      - ./secrets/packit/dev/id_rsa:/packit-ssh/id_rsa:ro,z
      - ./secrets/packit/dev/fedora.keytab:/secrets/fedora.keytab:ro,z
      - ./secrets/packit/dev/private-key.pem:/secrets/private-key.pem:ro,z
      #- .:/src:ro,z
    user: "1024"

  service:
    container_name: service
    build:
      context: .
      dockerfile: files/docker/Dockerfile
      args:
        SOURCE_BRANCH: main
    image: quay.io/packit/packit-service:dev
    command: /usr/bin/run_httpd.sh
    depends_on:
      - redis
      - postgres
    ports:
      - 8443:8443
    environment:
      DEPLOYMENT: dev
      REDIS_SERVICE_HOST: redis
      POSTGRESQL_USER: packit
      POSTGRESQL_PASSWORD: secret-password
      POSTGRESQL_HOST: postgres
      POSTGRESQL_DATABASE: packit
    volumes:
      - ./packit_service:/usr/local/lib/python3.9/site-packages/packit_service:ro,z
      - ./alembic:/src/alembic:ro,z
      - ./files/packit-httpd.conf:/etc/httpd/conf.d/packit-httpd.conf:ro,z
      # There's no secrets/ by default. You have to create (or symlink to other dir) it yourself.
      # Make sure to set `command_handler: local` since there is no kube in d-c
      - ./secrets/packit/dev/packit-service.yaml:/home/packit/.config/packit-service.yaml:ro,z
      - ./secrets/packit/dev/fedora.keytab:/secrets/fedora.keytab:ro,z
      - ./secrets/packit/dev/private-key.pem:/secrets/private-key.pem:ro,z
      - ./secrets/packit/dev/fullchain.pem:/secrets/fullchain.pem:ro,z
      - ./secrets/packit/dev/privkey.pem:/secrets/privkey.pem:ro,z
    user: "1024"

  fedora-messaging:
    container_name: fedora-messaging
    image: quay.io/packit/packit-service-fedmsg:dev
    depends_on:
      - redis
    environment:
      DEPLOYMENT: dev
      FEDORA_MESSAGING_CONF: /home/packit/.config/fedora.toml
      REDIS_SERVICE_HOST: redis
    volumes:
      # get it from secrets
      - ./secrets/packit/dev/fedora.toml:/home/packit/.config/fedora.toml:ro,Z
    user: "1024"

  centosmsg:
    container_name: centosmsg
    image: quay.io/packit/packit-service-centosmsg:dev
    depends_on:
      - redis
    environment:
      DEPLOYMENT: dev
      LOG_LEVEL: DEBUG
      REDIS_SERVICE_HOST: redis
    volumes:
      - ./secrets/packit/dev/centos-server-ca.cert:/secrets/centos-server-ca.cert:ro,Z
      - ./secrets/packit/dev/centos.cert:/secrets/centos.cert:ro,Z
    user: "1024"

  adminer:
    image: docker.io/adminer
    container_name: adminer
    depends_on:
      - postgres
    ports:
      - 8082:8080
    user: "1024"

  beat:
    container_name: beat
    build:
      context: .
      dockerfile: files/docker/Dockerfile.worker
      args:
        SOURCE_BRANCH: main
    image: quay.io/packit/packit-worker:dev
    command: /usr/bin/run_worker.sh
    depends_on:
      - redis
      - postgres
    environment:
      CELERY_COMMAND: beat
      DEPLOYMENT: dev
      REDIS_SERVICE_HOST: redis
      APP: packit_service.worker.tasks
      KRB5CCNAME: FILE:/tmp/krb5cc_packit
      POSTGRESQL_USER: packit
      POSTGRESQL_PASSWORD: secret-password
      POSTGRESQL_HOST: postgres
      POSTGRESQL_DATABASE: packit
      CELERY_RETRY_LIMIT: 0
      PUSHGATEWAY_ADDRESS: ""
    volumes:
      - ./packit_service:/usr/local/lib/python3.9/site-packages/packit_service:ro,z
      - ./secrets/packit/dev/packit-service.yaml:/home/packit/.config/packit-service.yaml:ro,z
      - ./secrets/packit/dev/copr:/home/packit/.config/copr:ro,z
      - ./secrets/packit/dev/ssh_config:/packit-ssh/config:ro,z
      - ./secrets/packit/dev/id_rsa.pub:/packit-ssh/id_rsa.pub:ro,z
      - ./secrets/packit/dev/id_rsa:/packit-ssh/id_rsa:ro,z
      - ./secrets/packit/dev/fedora.keytab:/secrets/fedora.keytab:ro,z
      - ./secrets/packit/dev/private-key.pem:/secrets/private-key.pem:ro,z
    user: "1024"
